name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.13
      uses: actions/setup-python@v3
      with:
        python-version: "3.13"

    - name: Install dependencies
      run: make install

    - name: Run tests
      run: make test

    - name: Lint code
      run: make lint

    - name: Format code
      run: make format

    - name: Run application
      run: make run

    - name: Clean up
      run: make clean
